### PR TITLE
Changed the order of details in the profile-details to improve layout

### PR DESCRIPTION
**Pull request by anishTP**
#### Before
Screenshot 2024-07-31 at 12 50 36 PM

#### After
Screenshot 2024-07-31 at 12 50 20 PM

### CODE REVIEW

**Comment by jace** [comment]
The bio is optional and of variable length, so the metadata (joined date, website) will float. IMO, these should be above to fix their position.

**Comment by jace** [comment]
This also needs screenshots in mobile layout to confirm the elements stack correctly.

**Comment by anishTP** [comment]
> The bio is optional and of variable length, so the metadata (joined date, website) will float. IMO, these should be above to fix their position.

When the bio is empty there won't be any empty space, if that is what you mean by metadata will float.
Screenshot 2024-07-31 at 1 22 20 PM

**Comment by anishTP** [comment]
> This also needs screenshots in mobile layout to confirm the elements stack correctly.

#### Before
Screenshot 2024-07-31 at 1 21 56 PM

#### After
Screenshot 2024-07-31 at 1 21 28 PM

**Comment by zainabbawa** [comment]
Screenshot 2024-07-31 1 28 26 PM
Here's a reference for how Twitter/X.com does it.

**Comment by jace** [comment]
Let's go with bio _above_ metadata then.

**Review by jace — APPROVED** [review]

**Pull request merged**
