### PR TITLE
Appframe

### PR DESCRIPTION
**Pull request by iambibhas**
Desktop

Dependency https://github.com/hasgeek/baseframe/pull/230

### CODE REVIEW

**Comment by jace** [comment]
Desktop footer needs to be cleaned up. Remove:

1. Twitter widget
2. Facebook widget
3. Physical address
4. Email/phone. Support links should be on a separate page

**Comment by jace** [comment]
In the calendar widget, the "Jun" should be on the following row alongside the dates, not the week days.

Project card

**Comment by jace** [comment]
The HasGeek logo isn't vertically centred in the header.

Header area

**Comment by jace** [comment]
The past project table is rendering as a responsive table for me. I'm using the Baseframe `navbar` branch.

Past project


IMO, past projects should not be displayed on the home page. They need a separate archive page.

**Comment by jace** [comment]
On mobile, the navbar displays on bottom on the home page but jumps to the top inside a project. This is jarring.

| Home | Project |
| --- | --- |
| Mobile home | Mobile project |

**Comment by jace** [comment]
The active tab in the navbar is not highlighted. It should be. (On desktop this will cause a very wide selected tab when the search input field is not present.)

**Comment by vidya-ram** [comment]
> In the calendar widget, the "Jun" should be on the following row alongside the dates, not the week days. The background colour on the dates should be the system selected text colour (defaulting to blue).
> 
> Project card

Fixed

**Comment by vidya-ram** [comment]
> The HasGeek logo isn't vertically centred in the header.
> 
> Header area

Fixed

**Comment by vidya-ram** [comment]
> The past project table is rendering as a responsive table for me. I'm using the Baseframe `navbar` branch.
> 
> Past project
> 
> IMO, past projects should not be displayed on the home page. They need a separate archive page.

Past projects section removed from home page.
Still showing past project on profile page.

**Comment by vidya-ram** [comment]
> Desktop footer needs to be cleaned up. Remove:
> 
> 1. Twitter widget
> 2. Facebook widget
> 3. Physical address
> 4. Email/phone. Support links should be on a separate page

Moved them to footer of about page

**Comment by vidya-ram** [comment]
> On mobile, the navbar displays on bottom on the home page but jumps to the top inside a project. This is jarring.
> 
> Home	Project
> Mobile home	Mobile project

Fixed

**Pull request merged**
