### PR TITLE
Better organize stylesheets

### PR DESCRIPTION
**Pull request by vidya-ram**
1. Move element tag styles out of `_layout.scss`. 
2. Move common stylesheets into `base` folder
3. Move component related styles into separate css files in the `components` folder
4. Remove unused styles from `header.scss` and move into components folder
5. Remove `mui-` prefix from funnel specific helper classes
6. Clean helper style file and rename to `_utils.scss`

### CODE REVIEW

**Comment by djamg** [comment]
- [ ] Changes in font-weight
IMG_3649
- [ ] Unexpected search icon in the nav bar on desktop
image

**Comment by anishTP** [comment]
Search-bar is broken in mobile

image

Home page search favicon color has changed on desktop

Live: image

Staging: 
image

Bottom padding in search bar projects page/crew tab has decreased.

Live:image

Staging:image

Padding margins changed in the admins search bar inside organization profile page:

Live: image

Staging: image

Card size in the search panel has changed:

Live: image

Staging: image

**Comment by anishTP** [comment]
Some elements sizes have tiny changes in the profile dropdown:

Live:image

Staging: image

Live: image

Staging: image

Background color of the bookmark icon has changed in a few projects:

Live: 
image

Staging: 
image

**Comment by vidya-ram** [comment]
> * [x]  Changes in font-weight - Fixed
>image

> * [x]  Unexpected search icon in the nav bar on desktop - Fixed
image

**Comment by vidya-ram** [comment]
* [x] Search-bar is broken in mobile - Fixed
* [x] Home page search favicon color has changed on desktop  - Fixed
* [x] Bottom padding in search bar projects page/crew tab has decreased.  - Fixed
* [x] Padding margins changed in the admins search bar inside organization profile page  - Fixed
* [x] Card size in the search panel has changed  - Fixed

**Comment by vidya-ram** [comment]
* [x] Some elements sizes have tiny changes in the profile dropdown:
**Now both org and more org of same size**
Screenshot 2023-01-13 at 11 02 24 AM
Screenshot 2023-01-13 at 11 02 03 AM
<hr>

* [x] Logo container size has changed slightly
**Now it center aligned**
Screenshot 2023-01-13 at 11 06 33 AM
Screenshot 2023-01-13 at 11 06 17 AM


* [] Background color of the bookmark icon has changed in a few projects:

**Comment by djamg** [comment]
Font weight for 'h' tags is broken

image

**Comment by vidya-ram** [comment]
> Font weight for 'h' tags is broken in markdown
> 
> image

Fixed

**Pull request merged**
